/**
 * lib/workflow/state-machine.ts
 *
 * #74 — Shared workflow state machine.
 * Defines allowed states, transitions, and side-effect hooks
 * for all workflow types (NPPES, payer directory, onboarding, etc.)
 */

// ── Workflow status enum ────────────────────────────────────

export const WORKFLOW_STATUSES = [
  'action_needed',
  'in_progress',
  'awaiting',
  'resolved',
  'cancelled',
] as const;

export type WorkflowStatus = (typeof WORKFLOW_STATUSES)[number];

// ── Task status enum ────────────────────────────────────────

export const TASK_STATUSES = ['pending', 'active', 'completed', 'skipped'] as const;

export type TaskStatus = (typeof TASK_STATUSES)[number];

// ── Valid transitions ───────────────────────────────────────

const WORKFLOW_TRANSITIONS: Record<WorkflowStatus, WorkflowStatus[]> = {
  action_needed: ['in_progress', 'cancelled'],
  in_progress: ['awaiting', 'resolved', 'action_needed', 'cancelled'],
  awaiting: ['resolved', 'action_needed', 'cancelled'],
  resolved: [], // terminal
  cancelled: [], // terminal
};

const TASK_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
  pending: ['active', 'skipped'],
  active: ['completed', 'pending', 'skipped'],
  completed: [], // terminal
  skipped: [], // terminal
};

// ── Transition result ───────────────────────────────────────

export type TransitionResult = {
  allowed: boolean;
  from: string;
  to: string;
  reason?: string;
};

// ── Validate transitions ────────────────────────────────────

export function canTransitionWorkflow(from: WorkflowStatus, to: WorkflowStatus): TransitionResult {
  if (from === to) {
    return { allowed: true, from, to, reason: 'No-op (same status)' };
  }
  const allowed = WORKFLOW_TRANSITIONS[from]?.includes(to) ?? false;
  return {
    allowed,
    from,
    to,
    reason: allowed
      ? undefined
      : `Cannot transition workflow from "${from}" to "${to}". Allowed: [${WORKFLOW_TRANSITIONS[from]?.join(', ')}]`,
  };
}

export function canTransitionTask(from: TaskStatus, to: TaskStatus): TransitionResult {
  if (from === to) {
    return { allowed: true, from, to, reason: 'No-op (same status)' };
  }
  const allowed = TASK_TRANSITIONS[from]?.includes(to) ?? false;
  return {
    allowed,
    from,
    to,
    reason: allowed
      ? undefined
      : `Cannot transition task from "${from}" to "${to}". Allowed: [${TASK_TRANSITIONS[from]?.join(', ')}]`,
  };
}

// ── Auto-derive workflow status from tasks ───────────────────

export function deriveWorkflowStatus(
  tasks: Array<{ status: string; task_type: string }>,
): WorkflowStatus {
  if (tasks.length === 0) return 'action_needed';

  const allCompleted = tasks.every((t) => t.status === 'completed' || t.status === 'skipped');
  if (allCompleted) return 'resolved';

  const hasMonitor = tasks.some(
    (t) => t.task_type === 'monitor_auto_confirm' && t.status === 'active',
  );
  if (hasMonitor) return 'awaiting';

  const hasActive = tasks.some((t) => t.status === 'active');
  if (hasActive) return 'in_progress';

  return 'action_needed';
}

// ── Event types generated by transitions ────────────────────

export type WorkflowEventType =
  | 'workflow_created'
  | 'workflow_status_changed'
  | 'task_status_changed'
  | 'task_completed'
  | 'task_activated'
  | 'approval_submitted'
  | 'correction_approved'
  | 'form_downloaded'
  | 'submission_marked'
  | 'auto_confirmed'
  | 'escalation_warning'
  | 'escalation_action'
  | 'workflow_resolved'
  | 'workflow_cancelled'
  | 'comment_added'
  | 'notification_sent';

export type WorkflowEvent = {
  workflow_id: string;
  event_type: WorkflowEventType;
  actor_id?: string;
  actor_type: 'user' | 'system' | 'cron';
  actor_email?: string;
  title: string;
  details?: Record<string, unknown>;
};

// ── Side effect definitions (for notifications) ─────────────

export type NotificationTrigger = {
  event_type: WorkflowEventType;
  email_template: string;
  recipient: 'practice_admin' | 'assigned_user' | 'all_practice_users';
  priority: 'high' | 'normal' | 'low';
};

export const NOTIFICATION_TRIGGERS: NotificationTrigger[] = [
  {
    event_type: 'workflow_created',
    email_template: 'workflow_created',
    recipient: 'practice_admin',
    priority: 'normal',
  },
  {
    event_type: 'task_activated',
    email_template: 'task_needs_attention',
    recipient: 'assigned_user',
    priority: 'high',
  },
  {
    event_type: 'auto_confirmed',
    email_template: 'auto_confirmed',
    recipient: 'practice_admin',
    priority: 'normal',
  },
  {
    event_type: 'escalation_warning',
    email_template: 'overdue_warning',
    recipient: 'practice_admin',
    priority: 'high',
  },
  {
    event_type: 'escalation_action',
    email_template: 'overdue_action',
    recipient: 'all_practice_users',
    priority: 'high',
  },
  {
    event_type: 'workflow_resolved',
    email_template: 'workflow_resolved',
    recipient: 'practice_admin',
    priority: 'low',
  },
];

// ── Helper: find which notification to trigger ──────────────

export function getNotificationsForEvent(eventType: WorkflowEventType): NotificationTrigger[] {
  return NOTIFICATION_TRIGGERS.filter((t) => t.event_type === eventType);
}
