#!/usr/bin/env python3
"""
NPPES Update Form PDF Generator
Generates pre-filled NPPES update forms as PDF artifacts for KairoLogic.

This script creates professional PDF documents that practices can download, review,
and submit to the NPPES portal (https://nppes.cms.hhs.gov).

Usage as a module:
    from generate_nppes_form import generate_nppes_form
    pdf_bytes = generate_nppes_form(data_dict)

Usage standalone:
    python generate_nppes_form.py
"""

from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.pdfgen import canvas as pdf_canvas
from reportlab.lib import colors


# KairoLogic brand color
KAIRO_BLUE = HexColor('#1F4E79')
LIGHT_GREY = HexColor('#F5F5F5')
DARK_TEXT = HexColor('#333333')


class NumberedCanvas(pdf_canvas.Canvas):
    """Custom canvas with header and footer for each page."""

    def __init__(self, *args, timestamp=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.timestamp = timestamp or datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    def showPage(self):
        """Add header and footer to each page before rendering."""
        self._add_header_footer()
        super().showPage()

    def _add_header_footer(self):
        """Draw header and footer."""
        width, height = letter

        # Header - KairoLogic branding
        self.setFont("Helvetica-Bold", 16)
        self.setFillColor(KAIRO_BLUE)
        self.drawString(0.5 * inch, height - 0.5 * inch, "KairoLogic")

        self.setFont("Helvetica", 10)
        self.setFillColor(DARK_TEXT)
        self.drawString(0.5 * inch, height - 0.75 * inch, "Provider Data Intelligence")

        # Header right side - title
        self.setFont("Helvetica-Bold", 14)
        self.setFillColor(KAIRO_BLUE)
        title_width = self.stringWidth("NPPES Update Request Form", "Helvetica-Bold", 14)
        self.drawString(width - 0.5 * inch - title_width, height - 0.5 * inch,
                       "NPPES Update Request Form")

        # Divider line
        self.setStrokeColor(KAIRO_BLUE)
        self.setLineWidth(2)
        self.line(0.5 * inch, height - 1 * inch, width - 0.5 * inch, height - 1 * inch)

        # Footer
        self.setFont("Helvetica", 8)
        self.setFillColor(grey)
        footer_text = f"Generated by KairoLogic — Provider Data Intelligence | {self.timestamp}"
        footer_width = self.stringWidth(footer_text, "Helvetica", 8)
        self.drawString(width / 2 - footer_width / 2, 0.4 * inch, footer_text)


def generate_nppes_form(data: dict) -> bytes:
    """
    Generate a pre-filled NPPES update form as a PDF.

    Args:
        data (dict): Dictionary containing:
            - practice_name (str): Name of the medical practice
            - npi_number (str): National Provider Identifier
            - provider_name (str): Name of the provider/practice manager
            - workflow_id (str): KairoLogic workflow reference ID
            - changes (list): List of change dictionaries with keys:
                - field (str): Field name being changed
                - current_value (str): Current NPPES value
                - corrected_value (str): Corrected value
                - source (str): Source of correction (e.g., "Website", "Phone call")
            - timestamp (str, optional): Generation timestamp

    Returns:
        bytes: PDF content as bytes

    Example:
        data = {
            'practice_name': 'Downtown Family Medicine',
            'npi_number': '1234567890',
            'provider_name': 'Sarah Johnson, MD',
            'workflow_id': 'WF-20260327-001',
            'changes': [
                {
                    'field': 'Phone',
                    'current_value': '(512) 555-1234',
                    'corrected_value': '(512) 555-5678',
                    'source': 'Website'
                }
            ]
        }
        pdf_bytes = generate_nppes_form(data)
    """

    # Set default timestamp if not provided
    if 'timestamp' not in data:
        data['timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    # Create PDF buffer
    pdf_buffer = BytesIO()

    # Create PDF document with custom canvas maker
    def canvas_maker(filename, **kwargs):
        return NumberedCanvas(filename, timestamp=data['timestamp'])

    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.5 * inch,
        leftMargin=0.5 * inch,
        topMargin=1.3 * inch,
        bottomMargin=0.7 * inch,
        title="NPPES Update Form"
    )

    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=KAIRO_BLUE,
        spaceAfter=12,
        fontName='Helvetica-Bold'
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=11,
        textColor=KAIRO_BLUE,
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )

    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        textColor=DARK_TEXT,
        spaceAfter=6
    )

    # Build document content
    content = []

    # Summary Section
    summary_data = [
        ['Practice Name:', data['practice_name']],
        ['NPI Number:', data['npi_number']],
        ['Provider/Manager:', data['provider_name']],
        ['Workflow ID:', data['workflow_id']],
        ['Date Generated:', data['timestamp'].split(' ')[0]],
    ]

    summary_table = Table(summary_data, colWidths=[2 * inch, 4 * inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LIGHT_GREY),
        ('TEXTCOLOR', (0, 0), (-1, -1), DARK_TEXT),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [white, LIGHT_GREY]),
    ]))

    content.append(Paragraph("Summary", heading_style))
    content.append(summary_table)
    content.append(Spacer(1, 12))

    # Changes Requested Section
    content.append(Paragraph("Changes Requested", heading_style))

    # Filter only changes where current != corrected
    changes = [c for c in data.get('changes', []) if c['current_value'] != c['corrected_value']]

    if changes:
        # Build changes table
        table_data = [
            ['Field', 'Current NPPES Value', 'Corrected Value', 'Source']
        ]

        for change in changes:
            table_data.append([
                change['field'],
                change['current_value'],
                change['corrected_value'],
                change['source']
            ])

        changes_table = Table(table_data, colWidths=[1.3 * inch, 1.5 * inch, 1.5 * inch, 1.2 * inch])
        changes_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), KAIRO_BLUE),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, LIGHT_GREY]),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        content.append(changes_table)
    else:
        content.append(Paragraph("No changes detected.", normal_style))

    content.append(Spacer(1, 14))

    # Submission Instructions Section
    content.append(Paragraph("Submission Instructions", heading_style))

    instructions = [
        ["1. Review Changes", "Carefully review all changes listed above to ensure accuracy."],
        ["2. Visit NPPES Portal", "Go to https://nppes.cms.hhs.gov and log in with your account."],
        ["3. Update Records", "Navigate to the provider record and make the corrections shown above."],
        ["4. Submit Changes", "Submit your updates through the portal."],
        ["5. Processing Time", "NPPES typically processes updates within 7-10 business days."],
        ["6. Confirmation", "KairoLogic will automatically confirm once NPPES reflects your updates."],
    ]

    instructions_table = Table(instructions, colWidths=[1.2 * inch, 4.8 * inch])
    instructions_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [white, LIGHT_GREY]),
    ]))

    content.append(instructions_table)
    content.append(Spacer(1, 14))

    # Authorization Section
    content.append(Paragraph("Authorization & Signature", heading_style))

    auth_text = (
        "By submitting this form to NPPES, I certify that I am authorized to make changes to this provider record "
        "and that the information provided is accurate and complete."
    )
    content.append(Paragraph(auth_text, normal_style))
    content.append(Spacer(1, 12))

    # Signature lines
    sig_data = [
        ['Authorized By (Print Name):', '_' * 50],
        ['Title:', '_' * 50],
        ['Date:', '_' * 50],
        ['Signature:', '_' * 50],
    ]

    sig_table = Table(sig_data, colWidths=[2 * inch, 4 * inch])
    sig_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
    ]))

    content.append(sig_table)

    # Build PDF
    doc.build(content, canvasmaker=canvas_maker)
    pdf_bytes = pdf_buffer.getvalue()
    pdf_buffer.close()

    return pdf_bytes


def main():
    """Generate a sample NPPES update form for demonstration."""

    # Sample data for a Texas medical practice
    sample_data = {
        'practice_name': 'Downtown Family Medicine',
        'npi_number': '1234567890',
        'provider_name': 'Dr. Michael Rodriguez',
        'workflow_id': 'WF-20260327-001',
        'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'changes': [
            {
                'field': 'Address Line 1',
                'current_value': '123 Oak Street',
                'corrected_value': '456 Oak Street',
                'source': 'Website'
            },
            {
                'field': 'Phone',
                'current_value': '(512) 555-1234',
                'corrected_value': '(512) 555-5678',
                'source': 'Website'
            },
            {
                'field': 'Fax',
                'current_value': '(512) 555-9999',
                'corrected_value': '(512) 555-8765',
                'source': 'Phone Verification'
            },
            {
                'field': 'Specialty/Taxonomy',
                'current_value': 'Family Medicine (207Q00000X)',
                'corrected_value': 'Family Medicine (207Q00000X)',
                'source': 'System'
            },
        ]
    }

    # Generate PDF
    pdf_bytes = generate_nppes_form(sample_data)

    # Save to file
    output_path = '/sessions/keen-stoic-brown/mnt/outputs/sample_nppes_update_form.pdf'
    with open(output_path, 'wb') as f:
        f.write(pdf_bytes)

    print(f"PDF generated successfully: {output_path}")
    print(f"PDF size: {len(pdf_bytes)} bytes")
    print(f"Practice: {sample_data['practice_name']}")
    print(f"NPI: {sample_data['npi_number']}")
    print(f"Changes: {len([c for c in sample_data['changes'] if c['current_value'] != c['corrected_value']])} fields updated")


if __name__ == '__main__':
    import sys
    import json

    # If called with input/output args from API route:
    #   python generate-nppes-form.py input.json output.pdf
    if len(sys.argv) == 3:
        input_path = sys.argv[1]
        output_path = sys.argv[2]
        with open(input_path, 'r') as f:
            api_data = json.load(f)

        # Map API format to generator format
        form_data = {
            'practice_name': api_data.get('practice_name', ''),
            'npi_number': api_data.get('npi', ''),
            'provider_name': api_data.get('provider_name', ''),
            'workflow_id': api_data.get('workflow_id', ''),
            'changes': [
                {
                    'field': c['field'],
                    'current_value': c['current_value'],
                    'corrected_value': c['corrected_value'],
                    'source': c.get('source', 'KairoLogic'),
                }
                for c in api_data.get('corrections', [])
            ],
        }

        pdf_bytes = generate_nppes_form(form_data)
        with open(output_path, 'wb') as f:
            f.write(pdf_bytes)
        print(f"Generated {output_path} ({len(pdf_bytes)} bytes)")
    else:
        main()
