export default function InsightsPage() {
  return (
    <div>
      <section className="bg-navy text-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-5xl font-display font-bold mb-4">Insights</h1>
          <p className="text-xl text-gray-300">
            Resources and technical analysis generated by the Sentry AI engine.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="text-6xl mb-6">📚</div>
          <h2 className="text-3xl font-display font-bold text-navy mb-4">
            Repository Empty
          </h2>
          <p className="text-gray-600 mb-8">
            No compliance resources have been indexed yet. Head to the Admin Portal to generate AI-backed statutory intelligence.
          </p>
        </div>
      </section>
    </div>
  );
}
